package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.28

import (
	"context"
	usecase "github.com/PGabrielDev/clean-archi-go/internal/usecases"

	"github.com/PGabrielDev/clean-archi-go/internal/infra/graph/model"
)

// CreateOrder is the resolver for the createOrder field.
func (r *mutationResolver) CreateOrder(ctx context.Context, input *model.OrderInput) (*model.Order, error) {
	orderEntity := usecase.OrderInputDTO{input.ID, input.Price, input.Tax}

	order, err := r.CreateOrderUseCase.Execute(orderEntity)

	if err != nil {
		return nil, err
	}

	output := &model.Order{
		ID:         order.ID,
		Price:      order.Price,
		Tax:        order.Tax,
		FinalPrice: order.FinalPrice,
	}

	return output, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
